name: Bulk close issues
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 0
          stale-issue-label: "stale"
          stale-issue-message: "This project is now in limited maintenance mode. All issues created before 2024 are being marked as stale."
          close-issue-message: "This issue was closed because it was marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 1000
